version: 2

sources:
  - name: raw
    database: healthcare_analytics
    schema: raw
    tables:
      - name: patients
      - name: doctors
      - name: departments
      - name: treatments
      - name: visits
